version: "3.5"
services:
  kenya_build_acts:
    build: .
    image: dnjau/kenya_build_acts_image:latest
    container_name: SMSManager
    command: bash -c "java -jar ./kenya_build_acts_javabackend/KenyaActs.jar"
    ports:
      - "8086:8086"
    volumes:
      - .:/kenya_build_acts_javabackend

